### ISSUE TITLE
Language list cut off

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#1]
Anything we can do now, or just log issue with Able Player?

Ref: https://www.w3.org/WAI/videos/standards-and-benefits.html

Screen grab: 
<img width="325" alt="langs-cut-off" src="https://user-images.githubusercontent.com/6991814/33574062-7882377c-d8fd-11e7-9dad-6038e6e0c566.png">

**Comment by yatil** [comment]
This is an issue with Ableplayer. File there: https://github.com/ableplayer/ableplayer/issues

**Comment by yatil** [comment]
This appears to be resolved in the new design: 
![Screenshot of fully visible language list](https://user-images.githubusercontent.com/58862/45149729-8d7ba180-b1ca-11e8-8c89-f4ef7f5caa55.png)
