### ISSUE TITLE
Languages in language ?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#10]
In the list of subtitles available, can we display the languages in their language? e.g., "Deutsche Untertitel" instead of "German subtitles"

**Comment by yatil** [comment]
The titles are specified in the `{% include video-player.html … %}` tag. However we cannot (as they are HTML attributes) set the language for those subtitle titles, so “Deutsche Untertitel” would be read by an English screen reader voice.

**Comment by yatil** [comment]
Okay, I’ll rewrite the component to use standard translations (once we have them) for the subtitle description in January and also fork able player to add lang attributes where needed.

**Comment by slhenry** [comment]
Cool. Let's figure out priority of this with all the other things needed.

**Comment by yatil** [comment]
This now just lists the language, e.g. “Deutsch”, “Français” which is how it is mostly done. It is clear from the context that it is subtitles/captions. This works now (= for a couple of days/weeks :-D) as intended.

**Comment by slhenry** [comment]
> It is clear from the context that it is subtitles/captions.

+1
