### ISSUE TITLE
Alternative to YouTube

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#11]
Add alternative way to see/get the video other than YouTube. and a subtitle file.

**Comment by yatil** [comment]
Uploaded to media.w3.org:

http://media.w3.org/2018/12/accessibility-introduction/

Someone needs to add links to the page.

**Comment by slhenry** [comment]
/me sent off-hub comment about URI. after that resolved, will update page. :-)

**Comment by yatil** [comment]
Now at http://media.w3.org/wai/accessibility-intro/
