### ISSUE TITLE
transcript with description format

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#12]
Ref: [Transcript with Description](https://www.w3.org/WAI/videos/standards-and-benefits/#transcript)

Gathering more input on best practices for providing a text transcript with descriptions.

Use cases:
* **people with limited &/or expensive bandwidth (e.g., in some rural areas around the world) who want to get the audio and visual content without streaming the video**
* people whose vision is too poor to reliably read captions and whose hearing is too poor to reliably hear dialogue and audio description ([Success Criterion 1.2.8: Media Alternative](https://www.w3.org/WAI/WCAG21/Understanding/media-alternative-prerecorded.html))
* screen reader users who process this better, faster, easier than audio described versions (or in this particular case where it doesn't warrant AD version, they're still curious about the visuals)
* ...

<s>(/me has call into @a11ycob :-)</s> _call completed!_

_Updated UI: Previous iteration had a first column with numbers 1, 2, 3..._

**Comment by slhenry** [comment]
Notes from call with @a11ycob _(feel free to edit)_
* looks good for the type of videos that we have on WAI site (educational rather than entertainment)
* consider timestamp instead of sequence number
* although probably better not to have either timestamp or sequence number

**Comment by slhenry** [comment]
Considerations:
* Table format allows users to choose to focus only on one column, or to read both.
* Timestamp may be better than sequence number.
* Timestamp or sequence number is cluttering, especially for screen readers. Is there an important reason to include either?

**Comment by yatil** [comment]
* Don’t care about including or not of sequence number/time stamp.
* Table Format always bad for responsive view, would prefer ordered list, I think.

**Comment by cochfarf** [comment]
I was thinking it made more sense as an ordered list rather than a table as well.

**Comment by yatil** [comment]
The HTML changed here: https://github.com/w3c/wai-video-standards-and-benefits/commit/f39d6209373d474e0b105445986643b56b68c412 – Now one column is extremely wide and the other one is extremely narrow. This looks bad. I would recommend spacing the columns more evenly (like before a 70%/30% split should look good.)

**Comment by slhenry** [comment]
> I would recommend spacing the columns more evenly (like before a 70%/30% split should look good.)

done.

**Comment by yatil** [comment]
From Laura in the survey:

> I think including timestamps can help with findability for longer videos. It allows users to locate content without re-watching the entire video to watch a clip they're looking for.

Depending on if able player supports this, we could add links/icons to jump to those places without writing out the minutes and seconds from the start.
