### ISSUE TITLE
Standard keyboard shortcuts are not working

### ISSUE THREAD

**Issue by hiroya-uga** [w3c/wai-video-standards-and-benefits#127]
## What's happened?

I can not use almost all keyboard shortcuts in:
https://www.w3.org/WAI/videos/standards-and-benefits/

## Expected Behavior

I can use all standard keyboard shortcuts.

## Current Behavior

I can not use almost all keyboard shortcuts. 
e.g. `cmd + f`, `cmd + r`.

**Comment by remibetin** [comment]
Thanks @hiroya-uga I will take a look.

**Comment by remibetin** [comment]
@hiroya-uga Thanks again! We have fixed the problem today. See for example https://www.w3.org/WAI/videos/standards-and-benefits/
