### ISSUE TITLE
Player in different languages?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#13]
https://ableplayer.github.io/ableplayer/#supported-languages

What are the issues with providing the player in different languages on translated pages?

**Comment by slhenry** [comment]
If not feasible, edit README https://github.com/w3c/wai-video-standards-and-benefits

**Comment by yatil** [comment]
Easy.

**Comment by yatil** [comment]
Turns out this happens automagically (if a translation is available), <a href="https://ableplayer.github.io/ableplayer/#language">see</a>:

> #### Language
> * data-lang - optional; specify language of the player using 2-character language code (default is “en” for English)
> * data-force-lang - optional; include this option to force the player to use the value of data-lang as the player language. Otherwise, the player language will be set as follows, in order of precedence: 1) the language of the web page or user’s web browser if either is known and if there is a matching translation file; 2) the value of data-lang if provided; 3) English.
