### ISSUE TITLE
[translation] Page heading may differ from page title

### ISSUE THREAD

**Issue by notabene** [w3c/wai-video-standards-and-benefits#16]
Re: https://github.com/w3c/wai-video-standards-and-benefits/blob/fr-translation/index.fr.md

In the meta stuff at the beginning of the translation there is this:
```
title: "Vidéo : introduction à l’accessibilité web et aux standards du W3C" # translate this
```
In French we need non-breakable spaces, so we may need one more line in translation notes, like this:
```
title: "Vidéo : introduction à l’accessibilité web et aux standards du W3C" # translate this
pageheading: "Vidéo&#8239;: introduction à l’accessibilité web et aux standards du W3C" # translate this
```

What do you think Eric? I’m sure this will pop up in many other languages.

(I’ll leave it untouched for the moment as it’s not important when the non-breaking space is after the first word, but food for thought etc.)

**Comment by notabene** [comment]
Darn, I can't assign. So here's a manual ping: @yatil :wave:

**Comment by yatil** [comment]
You can use `title_html:` for what you call `pageheading:`. Sorry I did not get to write any documentation before my vacation… And I’m obviously vacationing wrong :-)

**Comment by notabene** [comment]
Thanks and yes, true. ;)
