### ISSUE TITLE
Pointers to media alternatives on W3C servers not user friendly

### ISSUE THREAD

**Issue by yatil** [w3c/wai-video-standards-and-benefits#27]
The current display of videos available on the W3C server is a little bit confusing and not very user-friendly:

> This video information is available:
> 
> * **In different languages as subtitles** — [Instructions to see translations](https://w3c.github.io/wai-video-standards-and-benefits/videos/standards-and-benefits/#translations) are below
> * On YouTube: https://www.youtube.com/watch?v=20SHvU2PKsM
> * On the W3C website — video: http://media.w3.org/wai/accessibility-intro/intro.mp4, English captions/subtitles file (VTT): http://media.w3.org/wai/accessibility-intro/W3C_INTRO_SFHI.en.vtt, list of other language VTT files: http://media.w3.org/wai/accessibility-intro/
> * As a [Text Transcript with Description of Visuals](https://w3c.github.io/wai-video-standards-and-benefits/videos/standards-and-benefits/#transcript) below

![Screenshot of many raw URLs](https://user-images.githubusercontent.com/58862/53162448-51979580-35cc-11e9-877c-b26330ae6895.png)

1. I think it is somewhat weird to have the subtitles and transcript around two more external pointers
2. In the first bullet, I think the “Instructions to see translations” is misleading once we have launched the page translations.
3. So many raw links, that is hard to skim and also makes it harder for screen reader users.
4. On the W3C website is misleading as _this_ is the W3C website. So if they cannot see it, why should they be able to see it from here.
5. “Below” feels unnecessary.
6. Unsure if we need to bolden subtitles.

Proposal:

> This video information is available:
> 
> * In different languages as subtitles and as transcripts — [Instructions to see those languages](https://w3c.github.io/wai-video-standards-and-benefits/videos/standards-and-benefits/#translations)
> * As a [Text Transcript with Description of Visuals](https://w3c.github.io/wai-video-standards-and-benefits/videos/standards-and-benefits/#transcript)
> * [On YouTube](https://www.youtube.com/watch?v=20SHvU2PKsM)
> * On a W3C server — [video](http://media.w3.org/wai/accessibility-intro/intro.mp4), [English captions (VTT format)](http://media.w3.org/wai/accessibility-intro/W3C_INTRO_SFHI.en.vtt), [list of other language subtitles (VTT format)](http://media.w3.org/wai/accessibility-intro/)

(Caption: Text in the language of the video, Subtitle: text in a language other than the video language.)

**Comment by slhenry** [comment]
Thanks for the input. I made most of the changes, with a few tweaks. :-)

fyi:
* "Below" is helpful for people to know that they are not leaving this page. (only some people can tell that from hovering and looking at the URI :-)
* Yes, I know the distinction between captions and subtitles -- although it is not as clear in some languages. I was trying to make the translation as straightforward as possible.
