### ISSUE TITLE
Translation in Greek for the video "Introduction to Web Accessibility and W3C Standards"

### ISSUE THREAD

**Issue by pkoutsod** [w3c/wai-video-standards-and-benefits#3]
Hi!

On Mar 15, 2018, 1:12 AM I sent at wai@w3.org (as suggested on the web page) the attached W3C_INTRO_SFHI_EL.zip which is the **greek translation** for the video "**Introduction to Web Accessibility and W3C Standards**" found at https://www.w3.org/WAI/videos/standards-and-benefits

I received the automatic email found bellow.

I was wondering if anyone has checked the suggested .vvt that I sent.

Best,
Panos Kοutsodimitropoulos

Attached file:
[W3C_INTRO_SFHI_EL.zip](https://github.com/w3c/wai-video-standards-and-benefits/files/2061440/W3C_INTRO_SFHI_EL.zip)

----

**Auto - response sent by wai-request@w3.org**

from: | wai-request@w3.org
to: | pkoutsod@gmail.com
date: | Mar 15, 2018, 1:12 AM
subject: | Re: Translation in Greek for the video Introduction to Web Accessibility and W3C Standards
mailed-by: | listhub.w3.org

*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

**Comment by yatil** [comment]
Hi @pkoutsod, sorry for not getting back to you. Indeed the email never made it to us, so thanks for trying it again. I hope to add the translation soon.

**Comment by pkoutsod** [comment]
Hi @yatil! Thanks for the feedback :-)
When you add the translation, can you please let me know? :-)

**Comment by yatil** [comment]
@pkoutsod Sure! :-)

**Comment by yatil** [comment]
@nitedog I added Hungarian and Greek and put the resource into the new layout. A preview is here: https://w3c.github.io/wai-video-standards-and-benefits/videos/standards-and-benefits/

New subtitles can be added here: https://github.com/w3c/wai-video-standards-and-benefits/blob/master/index.md (Yes, it is one long comma-separated string with pipe-separated data. This is very editor hostile :-/ I made myself a todo to simplify it.)

**Comment by nitedog** [comment]
Thanks!
