### ISSUE TITLE
Dutch player not translated

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#33]
(all others worky !)

**Comment by yatil** [comment]
Is there a durch translation of able player? If not there is nothing I can do.

**Comment by yatil** [comment]
Looks to me like the language detection of able player fails for some reason:

https://github.com/ableplayer/ableplayer/blob/master/README.md#language

> Language
>
> * data-lang - optional; specify language of the player using 2-character language code (default is "en" for English)
> * data-force-lang - optional; include this option to force the player to use the value of data-lang as the player language. Otherwise, the player language will be set as follows, in order of precedence: 1) the language of the web page or user's web browser if either is known and if there is a matching translation file; 2) the value of data-lang if provided; 3) English.

**Comment by yatil** [comment]
Specified the data-lang attribute which should not be necessary, but that will fix it when it is regenerated.

**Comment by slhenry** [comment]
Great! Thanks! It's working now in the preview so I can get the screen capture. :-)

**Comment by yatil** [comment]
Looks like fixing this issue broke the player in Greece & Russian.

**Comment by yatil** [comment]
The Dutch translation is disabled in ableplayer and overwriting it broke than it fixed. I hope ableplayer will enable Dutch again, see: https://github.com/ableplayer/ableplayer/issues/355

**Comment by yatil** [comment]
I have now added a work-around that enables Dutch but leaves other translations alone. Keeping this issue open in the hope of a non-work-around solution.

**Comment by terrill** [comment]
The Dutch translation of Able Player needs to be updated. We added some new language a while ago that hasn't been translated yet. If someone would be willing to translate the content that's still in English in the Dutch translation file ([translations/nl.js](https://github.com/ableplayer/ableplayer/blob/develop/translations/nl.js)), then either send me the file or issue a pull request, we can get that working again. Thanks!

**Comment by yatil** [comment]
Fixed with the latest Ableplayer update.
