### ISSUE TITLE
[not showstopper] extra spaces after links

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#34]
> WAI website — to find a wide range of resources on different aspects of web accessibility standards , [education](@@) , [testing/evaluation](@@) , [project management, and policy](@@) .

/me assumes this is an issue with {% include link.html to="/teach-advocate/" text="education" %} that is broader than just this page, but not sure where @yatil would like it logged.

I think not a show stopper for soft launch, yet medium priority for after that -- hopefully before vacation. :-)

**Comment by yatil** [comment]
Fixed here: https://github.com/w3c/wai-website-theme-beta/commit/b2e93072a89e491b9cc976ccf46c127990b333da
