### ISSUE TITLE
[ja] in About Translation box, too much is linked not to the right place

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#41]
@yatil - I looked at it a little and couldn't find the problem. Please take a look. Thanks.

**Comment by yatil** [comment]
The closing '</a>' is missing from this translation string. Unfortunately, this issue does not say where the link should end, so I couldn’t fix it. (My Japanese is very rusty! ;-D)

https://github.com/w3c/wai-website-data/blob/master/translations.yml#L444

**Comment by slhenry** [comment]
Thanks for finding the source of the bug!

[fixed](https://github.com/w3c/wai-website-data/commit/edb11f8bbeb2c59feb64c0697967e8292a1e2acd#diff-9d31a970248a8964164d48b618b6060b)
