### ISSUE TITLE
Change translation instructions to CC area instead of transcript area ?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-video-standards-and-benefits#9]
https://www.w3.org/WAI/videos/standards-and-benefits/#translations

The instructions are for the translation to be in a separate transcript area. However, in some configurations (like mine), the transcript area cannot be seen along with the video.

Users can also get the translated text located where closed captions usually are -- which is more common for subtitles.

Do you remember the reasons why we chose to give the instructions for the transcript box instead of the CC area? (Possibly no reason other than that I had the transcript box open when I was writing up the instructions. :-/) Perhaps it was so screen reader users can the translation from the transcript box?  Although I think most screen readers access most captions files. Also, when we have the full page translated, that won't be necessary since they can get it in the "Transcript with Description" section.

I propose that we change the instructions to **_either_**:
* the captions area only
* both areas, with the captions area first &mdash; like this:

> To see a translation in the captions area at the bottom of the video:
> 1. Select “Captions”.
> 2. Select the language.

> To see a translation in a separate transcript area:
> 1. Select “Show transcript”.
> 2. Use the Language drop-down to select subtitles.

I **_mildly_** think it's not worth the added complexity to include both, yet could very easily be convinced to include both.

@yatil, @nitedog, Judy, others: Any thoughts?

**Comment by slhenry** [comment]
heh. to note: we didn't design that UI. :-)

I'd be inclined to support having the instructions at the bottom, **_if_** the rest of the page content were "meaty/tofu-y". However, it's not. The video itself is the only significant content on that page and the rest just supports the video (plus a "Learn More").

**Comment by yatil** [comment]
I think the learn more is important and we want to use the same way to present the information on the perspective videos eventually. However, I don’t feel strongly.

**Comment by slhenry** [comment]
> we want to use the same way to present the information on the perspective videos eventually

Ah, good point. I'll re-think it...

**Comment by slhenry** [comment]
Done:
* moved the instructions to the bottom, and added a link to it near the top, under the video player
* included both CC and transcript instructions
